default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV['DOCKER_IP'] %>
  port: 5432
  username: postgres
  password:

development:
  <<: *default
  database: fig_demo_development

test:
  <<: *default
  database: fig_demo_test

production:
  <<: *default
  database: fig_demo_production
